// packages/react/src/useWallet.tsx
import { useStore } from "@nanostores/react"
import { Cluster, initStore } from "@solana-wallets-solid/core"
import { createContext, useContext, useEffect } from "react"

export type WalletProviderProps = {
  autoConnect: boolean
  disconnectOnAccountChange: boolean
  env?: Cluster
  localStorageKey: string
  children?: React.ReactNode
}

export type WalletContext = {
  wallets: ReturnType<ReturnType<typeof initStore>["$wallets"]["get"]>
  walletsByName: ReturnType<ReturnType<typeof initStore>["$walletsMap"]["get"]>
  connectedAccount: ReturnType<ReturnType<typeof initStore>["$connectedAccount"]["get"]>
  connected: ReturnType<ReturnType<typeof initStore>["$isConnected"]["get"]>
  wallet: ReturnType<ReturnType<typeof initStore>["$wallet"]["get"]>
  env: ReturnType<ReturnType<typeof initStore>["$env"]["get"]>
  connecting: ReturnType<ReturnType<typeof initStore>["$connecting"]["get"]>
  disconnecting: ReturnType<ReturnType<typeof initStore>["$disconnecting"]["get"]>
  signMessage: ReturnType<typeof initStore>["signMessage"]
  signTransaction: ReturnType<typeof initStore>["signTransaction"]
  signAllTransactions: ReturnType<typeof initStore>["signAllTransactions"]
  sendTransaction: ReturnType<typeof initStore>["sendTransaction"]
}
const WalletContext = createContext<WalletContext>({} as WalletContext)

const {
  $wallet,
  $connectedAccount,
  $connecting,
  $disconnecting,
  $isConnected,
  initOnMount,
  $env,
  $wallets,
  $walletsMap,
  signMessage,
  sendTransaction,
  signTransaction,
  signAllTransactions,
} = initStore()

const WalletProvider: React.FC<WalletProviderProps> = ({ children, ...config }) => {
  const wallets = useStore($wallets)
  const walletsByName = useStore($walletsMap)
  const connectedAccount = useStore($connectedAccount)
  const connected = useStore($isConnected)
  const wallet = useStore($wallet)
  const env = useStore($env)
  const connecting = useStore($connecting)
  const disconnecting = useStore($disconnecting)

  useEffect(() => {
    const cleanup = initOnMount()
    return cleanup
  }, [])

  return (
    <WalletContext.Provider
      value={{
        wallets,
        walletsByName,
        connectedAccount,
        connected,
        wallet,
        env,
        connecting,
        disconnecting,
        signMessage,
        signTransaction,
        signAllTransactions,
        sendTransaction,
      }}
    >
      {children}
    </WalletContext.Provider>
  )
}
function useWallet() {
  return useContext(WalletContext)
}
export { useWallet, WalletProvider }

// packages/solid-1.0/src/useWallet.ts
import { useStore } from "@nanostores/solid"
import { createEffect, onCleanup, onMount } from "solid-js"
import {
  initStore,
  dispatchConnect,
  dispatchDisconnect,
  StoreProps,
} from "@solana-wallets-solid/core-1.0"

import { createContextProvider } from "./context"

const [WalletProvider, _useWallet] = createContextProvider((props: StoreProps) => {
  const {
    $wallet,
    $connectedAccount,
    $connecting,
    $disconnecting,
    $isConnected,
    initOnMount,
    $env,
    $wallets,
    $walletsMap,
    signMessage,
    sendTransaction,
    signTransaction,
    signAllTransactions,
  } = initStore({
    env: props.env,
    autoConnect: props.autoConnect,
    disconnectOnAccountChange: props.disconnectOnAccountChange,
    localStorageKey: props.localStorageKey,
    additionalWallets: props.additionalWallets,
  })
  const wallets = useStore($wallets)
  const walletsByName = useStore($walletsMap)
  const connectedAccount = useStore($connectedAccount)
  const connected = useStore($isConnected)
  const wallet = useStore($wallet)
  const env = useStore($env)
  const connecting = useStore($connecting)
  const disconnecting = useStore($disconnecting)

  onMount(() => {
    const cleanup = initOnMount()
    if (cleanup) {
      onCleanup(() => {
        cleanup()
      })
    }
  })

  createEffect(() => {
    console.log("env value: ", { env: env() })
  })

  return {
    env,
    connected,
    connecting,
    disconnecting,
    localStorageKey: props.localStorageKey,
    connectedAccount,
    wallet,
    wallets,
    walletsByName,

    connect: dispatchConnect,
    disconnect: dispatchDisconnect,

    signMessage,
    sendTransaction,
    signTransaction,
    signAllTransactions,
  }
})

const useWallet = () => {
  const context = _useWallet()
  if (!context) {
    throw new Error("useWallet must be used within a WalletProvider")
  }
  return context
}

export { WalletProvider, useWallet }
