// packages/react-1.0/src/useWallet.tsx
import { useStore } from "@nanostores/react"
import { initStore, StoreProps } from "@solana-wallets-solid/core-1.0"
import { createContext, useContext, useEffect, useRef } from "react"

export type WalletProviderProps = StoreProps & {
  children?: React.ReactNode
}

export type WalletContext = {
  wallets: ReturnType<ReturnType<typeof initStore>["$wallets"]["get"]>
  walletsByName: ReturnType<ReturnType<typeof initStore>["$walletsMap"]["get"]>
  connectedAccount: ReturnType<ReturnType<typeof initStore>["$connectedAccount"]["get"]>
  connected: ReturnType<ReturnType<typeof initStore>["$isConnected"]["get"]>
  wallet: ReturnType<ReturnType<typeof initStore>["$wallet"]["get"]>
  env: ReturnType<ReturnType<typeof initStore>["$env"]["get"]>
  connecting: ReturnType<ReturnType<typeof initStore>["$connecting"]["get"]>
  disconnecting: ReturnType<ReturnType<typeof initStore>["$disconnecting"]["get"]>
  signMessage: ReturnType<typeof initStore>["signMessage"]
  sendTransaction: ReturnType<typeof initStore>["sendTransaction"]
  signTransaction: ReturnType<typeof initStore>["signTransaction"]
  signAllTransactions: ReturnType<typeof initStore>["signAllTransactions"]
}
const WalletContext = createContext<WalletContext>({} as WalletContext)

const WalletProvider: React.FC<WalletProviderProps> = ({ children, ...config }) => {
  const store = useRef<ReturnType<typeof initStore>>(initStore(config))

  const wallets = useStore(store.current.$wallets)
  const walletsByName = useStore(store.current.$walletsMap)
  const connectedAccount = useStore(store.current.$connectedAccount)
  const connected = useStore(store.current.$isConnected)
  const wallet = useStore(store.current.$wallet)
  const env = useStore(store.current.$env)
  const connecting = useStore(store.current.$connecting)
  const disconnecting = useStore(store.current.$disconnecting)

  useEffect(() => {
    const cleanup = store.current.initOnMount()
    return cleanup
  }, [])

  return (
    <WalletContext.Provider
      value={{
        wallets,
        walletsByName,
        connectedAccount,
        connected,
        wallet,
        env,
        connecting,
        disconnecting,
        signMessage: store.current.signMessage,
        sendTransaction: store.current.sendTransaction,
        signTransaction: store.current.signTransaction,
        signAllTransactions: store.current.signAllTransactions,
      }}
    >
      {children}
    </WalletContext.Provider>
  )
}
function useWallet() {
  return useContext(WalletContext)
}
export { useWallet, WalletProvider }

// packages/solid-1.0/src/useWallet.ts
import { useStore } from "@nanostores/solid"
import { createEffect, onCleanup, onMount } from "solid-js"
import {
  initStore,
  dispatchConnect,
  dispatchDisconnect,
  StoreProps,
} from "@solana-wallets-solid/core-1.0"

import { createContextProvider } from "./context"

const [WalletProvider, _useWallet] = createContextProvider((props: StoreProps) => {
  const {
    $wallet,
    $connectedAccount,
    $connecting,
    $disconnecting,
    $isConnected,
    initOnMount,
    $env,
    $wallets,
    $walletsMap,
    signMessage,
    sendTransaction,
    signTransaction,
    signAllTransactions,
  } = initStore({
    env: props.env,
    autoConnect: props.autoConnect,
    disconnectOnAccountChange: props.disconnectOnAccountChange,
    localStorageKey: props.localStorageKey,
    additionalWallets: props.additionalWallets,
  })
  const wallets = useStore($wallets)
  const walletsByName = useStore($walletsMap)
  const connectedAccount = useStore($connectedAccount)
  const connected = useStore($isConnected)
  const wallet = useStore($wallet)
  const env = useStore($env)
  const connecting = useStore($connecting)
  const disconnecting = useStore($disconnecting)

  onMount(() => {
    const cleanup = initOnMount()
    if (cleanup) {
      onCleanup(() => {
        cleanup()
      })
    }
  })

  createEffect(() => {
    console.log("env value: ", { env: env() })
  })

  return {
    env,
    connected,
    connecting,
    disconnecting,
    localStorageKey: props.localStorageKey,
    connectedAccount,
    wallet,
    wallets,
    walletsByName,

    connect: dispatchConnect,
    disconnect: dispatchDisconnect,

    signMessage,
    sendTransaction,
    signTransaction,
    signAllTransactions,
  }
})

const useWallet = () => {
  const context = _useWallet()
  if (!context) {
    throw new Error("useWallet must be used within a WalletProvider")
  }
  return context
}

export { WalletProvider, useWallet }
